# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e12516a97ebc646b0a413f8eb4bfe099b4a233f35d7069a36d700a6d4d6e6765d48476d5f3fb7f6805ac30d32f23a87fbe8642901e71f9e2321cb68bf1be7437

test:
  secret_key_base: 045323208efff27bebb7dab4a23b3f3e3a00caad346f934b611501632c6974a0974ac75e252f127f0e70708125a85c3751f0369af51036514e69fa1bb900519e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
